apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: tt4kw71nt-go 
  janus-idp.io/tekton: tt4kw71nt-go
  backstage.io/kubernetes-id: tt4kw71nt-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: tt4kw71nt-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml